spring:
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://admin:password@localhost:27017/swiggyCloneDB?authSource=admin}
    auto-index-creation: true

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"