spring:
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://admin:password@localhost:27017/swiggyCloneDB?authSource=admin}
    auto-index-creation: true

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      username: ${SPRING_REDIS_USERNAME:}
      password: ${SPRING_REDIS_PASSWORD:}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-my-super-secret-key}
  expiration: ${JWT_EXPIRATION:86400000}